export const DEL_ARTICLE='DEL_ARTICLE'

export const GET_ARTICLE_LIST='GET_ARTICLE_LIST'

export const GET_ARTICLE_DETIAL='GET_ARTICLE_DETIAL'

export const GET_ARTICLE_LIST_ASYNC='GET_ARTICLE_LIST_ASYNC'

export const GET_ARTICLE_DETIAL_ASYNC='GET_ARTICLE_DETIAL_ASYNC'

export const GET_ARTICLE_LIST_PRE='GET_ARTICLE_LIST_PRE'


